version: '2'
services:
  pro-epargne-api:
    container_name: pro-epargne-api
    image: mchekini/pro-epargne-api:1.0
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: pro-epargne