version: '3'
services:
  pro-epargne-api:
    image: mchekini/pro-epargne-api:1.0
    container_name: pro-epargne-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=int
  pro-epargne-db:
    image: postgres
    container_name: pro-epargne-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

networks:
  default:
    external:
      name: pro-epargne