version: '3'
services:
  pro-epargne-api:
    image: mchekini/pro-epargne-api:1.0
    container_name: pro-epargne-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=int
      - SPRING_CLOUD_VAULT_TOKEN=${VAULT_TOKEN}
  pro-epargne-db:
    image: postgres
    container_name: pro-epargne-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pg-conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

networks:
  default:
    external:
      name: pro-epargne