app:
  name: pro_epargne
  version: 1.0.0



spring:
  datasource:
#    url: jdbc:postgresql://pro-epargne-db:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.check-consulting.net/auth/realms/master
          jwk-set-uri: https://keycloak.check-consulting.net/auth/realms/master/protocol/openid-connect/certs


server:
  port: 8082