app:
  name: pro_epargne
  version: 1.0.0


spring:
  datasource:
    url: jdbc:postgresql://pro-epargne-db:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver