apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app.kubernetes.io/name: pro-epargne-db
      app.kubernetes.io/instance: pro-epargne-api-db